// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkjOVJZiBKxapWMJKgZD7MydlQGYAoqms',
    appId: '1:366418846443:android:467008be10e7bc514794ae',
    messagingSenderId: '366418846443',
    projectId: 'nroq-crash',
    storageBucket: 'nroq-crash.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCmRgQFCTIHXv09hj5gklvtFKBzvkUJMl8',
    appId: '1:366418846443:ios:0d4a8956b3b3c6514794ae',
    messagingSenderId: '366418846443',
    projectId: 'nroq-crash',
    storageBucket: 'nroq-crash.firebasestorage.app',
    iosBundleId: 'com.example.wordFrontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCmRgQFCTIHXv09hj5gklvtFKBzvkUJMl8',
    appId: '1:366418846443:ios:0d4a8956b3b3c6514794ae',
    messagingSenderId: '366418846443',
    projectId: 'nroq-crash',
    storageBucket: 'nroq-crash.firebasestorage.app',
    iosBundleId: 'com.example.wordFrontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAL8VsDJcBGUZ_yPwhhfeMYaZOKMcW9rx8',
    appId: '1:366418846443:web:23778e2fd62539e94794ae',
    messagingSenderId: '366418846443',
    projectId: 'nroq-crash',
    authDomain: 'nroq-crash.firebaseapp.com',
    storageBucket: 'nroq-crash.firebasestorage.app',
    measurementId: 'G-2DL3RYEHQL',
  );
}
